version: "3.3"
services:
  notebook:
    image: mecab-base-notebook
    container_name: "exchange_ingredients"
    build: .
    # ポートの設定("ホスト：コンテナ")
    ports:
      - "1919:8888"
    # ボリューム(データの永続化の場所)の設定(ホスト:コンテナ)
    # ホスト内のworkディレクトリとコンテナ内の/workディレクトリが紐づいているイメージ
    volumes:
      - ./work:/home/jovyan/work